const dataSource = [
    {
      key: '1',
      executiveLegislative: 'LEGISLATIVE',
      fundCode: '223 (1-07-05-030) INFORMATION & COMMUNICATION TECHNOLOGY',
      dateAcquired: '2024',
      article: 'PRINTER',
      description: 'EPSON L121 ECOTANK SN: X9LV125362',
      propertyNo: 'FIS',
      unitValue: '15,000.00',
      onHandPerCard: '1',
      agencyName: 'TRICYCLE FRANCHISING BOARD',
      accountableOfficerName: 'COUN. RAM MEDALLA',
      designation: 'CHAIRMAN',
      disposeOrTransfer: '0',
      remarks: 'NDHC Sakalam',
    },
    {
      key: '2',
      executiveLegislative: 'LEGISLATIVE',
      fundCode: 'fundCode temp',
      dateAcquired: '2022',
      article: 'SHREDDER',
      description: 'CHUCK NORIS SHREDDER SN: 666XXXNSFW',
      propertyNo: 'FIS',
      unitValue: '100,000.00',
      onHandPerCard: '5',
      agencyName: 'NDHC MALUPITON BRANCH',
      accountableOfficerName: 'Cong. Guile Gabriel Javong',
      designation: 'Congressman',
      disposeOrTransfer: '0',
      remarks: 'Too sharp',
    },
    {
      key: '3',
      executiveLegislative: 'LEGISLATIVE',
      fundCode: '102 (2-34-56-789)',
      dateAcquired: '2021',
      article: 'DESK',
      description: 'WOODEN DESK SN: WD987654',
      propertyNo: '112233',
      unitValue: '5,000.00',
      onHandPerCard: '3',
      agencyName: 'CITY PLANNING OFFICE',
      accountableOfficerName: 'MR. JOHN DOE',
      designation: 'PLANNER',
      disposeOrTransfer: '0',
      remarks: 'Needs repair',
    },
  ];
  
  export default dataSource;
  